[package]
name = "duid-components"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#duid = { version = "0.1", features = ["default"] }
duid = { version = "0.2", git = "https://github.com/djedou/duid" , branch = "feat/dom_without_patches" }