[package]
name = "button_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
duid-ui = { path = "../../" }
wasm-bindgen = "0.2"


[profile.release]
debug = true
lto = true